// <auto-generated />
using System;
using Fluentra.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fluentra.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721221907_ExpandSceneTranslations")]
    partial class ExpandSceneTranslations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fluentra.Domain.Entities.Shadowing.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int")
                        .HasColumnName("sequence_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<string>("TranslationEs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("translation_es");

                    b.Property<string>("TranslationFr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("translation_fr");

                    b.Property<string>("TranslationPt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("translation_pt");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_scenes");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_scenes_video_id");

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("Fluentra.Domain.Entities.Shadowing.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time")
                        .HasColumnName("duration");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.Property<string>("YouTubeVideoId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("you_tube_video_id");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("YouTubeVideoId")
                        .IsUnique()
                        .HasDatabaseName("ix_videos_you_tube_video_id");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("Fluentra.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Fluentra.Infrastructure.ExternalServices.Shadowing.YouTubeQuotaUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("UnitsConsumed")
                        .HasColumnType("int")
                        .HasColumnName("units_consumed");

                    b.HasKey("Id")
                        .HasName("pk_youtube_quota_usage");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("ix_youtube_quota_usage_date");

                    b.ToTable("youtube_quota_usage", (string)null);
                });

            modelBuilder.Entity("Fluentra.Domain.Entities.Shadowing.Scene", b =>
                {
                    b.HasOne("Fluentra.Domain.Entities.Shadowing.Video", null)
                        .WithMany("Scenes")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scenes_videos_video_id");

                    b.OwnsOne("Fluentra.Domain.ValueObjects.Shadowing.SceneTiming", "Timing", b1 =>
                        {
                            b1.Property<int>("SceneId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<TimeSpan>("End")
                                .HasColumnType("time")
                                .HasColumnName("end_time");

                            b1.Property<TimeSpan>("Start")
                                .HasColumnType("time")
                                .HasColumnName("start_time");

                            b1.HasKey("SceneId");

                            b1.ToTable("scenes");

                            b1.WithOwner()
                                .HasForeignKey("SceneId")
                                .HasConstraintName("fk_scenes_scenes_id");
                        });

                    b.Navigation("Timing")
                        .IsRequired();
                });

            modelBuilder.Entity("Fluentra.Domain.Entities.Shadowing.Video", b =>
                {
                    b.Navigation("Scenes");
                });
#pragma warning restore 612, 618
        }
    }
}
